In [1]:
import pandas as pd

In [2]:
movies_raw = pd.read_table('movie.metadata.tsv', names=['wikipedia_ID', 'freebase_ID', 'name', 'release_date', 'box_office', 'runtime', 'languages', 'countries', 'genres'])
movies_raw.head()

,wikipedia_ID,freebase_ID,name,release_date,box_office,runtime,languages,countries,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"

In [9]:
movies_raw.shape

(81741, 9)

In [3]:
ids = pd.read_table('wikidata_freebase_imdb.tsv', names=['wikidata_ID', 'freebase_ID', 'IMDB_ID'], header=0)
ids.head()

                            wikidata_ID freebase_ID    IMDB_ID
0   http://www.wikidata.org/entity/Q595  /m/0hgqwpj  tt1675434
1   http://www.wikidata.org/entity/Q961  /m/027zfqr  tt0065035
2   http://www.wikidata.org/entity/Q990   /m/083whx  tt0120948
3  http://www.wikidata.org/entity/Q2345    /m/0m_tj  tt0050083
4  http://www.wikidata.org/entity/Q3997  /m/0jzsdw1  tt4168940

In [4]:
ids.wikidata_ID = ids.wikidata_ID.str[31:].copy()

In [46]:
# Quelles valeurs dupliquées garde-ton ?
ids[ids.duplicated('freebase_ID', keep=False)].sort_values('freebase_ID').iloc[60:120]

       wikidata_ID  freebase_ID     IMDB_ID
104075    Q3591487  /m/012dvhj6   tt0224450
104074    Q3520769  /m/012dvhj6   tt0224450
154704   Q12976869  /m/012dvwf7  tt18273814
155946   Q12976869  /m/012dvwf7   tt5544546
156220   Q19363954  /m/012n8g2y   tt4767814
95782    Q19363954  /m/012n8g2y   tt4065306
153507   Q25136226  /m/012sttqd   tt0016715
156373   Q25136226  /m/012sttqd   tt0017003
56691    Q19895890  /m/012vhjbs   tt0249962
56692    Q19895890  /m/012vhjbs   tt0262769
19100    Q19893352  /m/0131zyqx   tt0022543
45259     Q2534628  /m/0131zyqx   tt0179094
16419    Q16855919  /m/01347wnc   tt0023365
156186   Q16855919  /m/01347wnc   tt0130203
155850   Q19880914  /m/0134d1wz   tt4021118
38174    Q19880914  /m/0134d1wz   tt1349642
155851   Q19911394  /m/0138ghky   tt4597838
38417    Q19911394  /m/0138ghky   tt4422836
155870   Q19954955  /m/0138jqs2   tt5588670
153099   Q19954955  /m/0138jqs2   tt9010756
155852   Q19954850  /m/0138n2m3   tt4401014
38215    Q19954850  /m/0138n2m3   tt2182400
18608    Q20649655  /m/013chnsl   tt0169862
18694    Q20649655  /m/013chnsl   tt0020854
20565      Q499767    /m/014l6l   tt0159881
20564      Q499767    /m/014l6l   tt0057758
66189     Q3987083   /m/01fdrnh   tt3647778
66190     Q3987083   /m/01fdrnh   tt3647810
66191     Q3987083   /m/01fdrnh   tt3647864
126029    Q6497116    /m/01g3lv  tt15421956
126028    Q6497116    /m/01g3lv  tt15421926
128232    Q6497116    /m/01g3lv   tt0158814
3699      Q1887148    /m/01gy2v   tt9642938
3698      Q1887148    /m/01gy2v   tt0094574
61966     Q1247647    /m/01n92l   tt0058846
61965     Q1247647    /m/01n92l   tt0053496
78858      Q409389    /m/01rny2   tt0086662
78859      Q409389    /m/01rny2   tt0166030
93072     Q1248126    /m/01xp3p   tt0335698
137377    Q1248126    /m/01xp3p   tt0047701
155965    Q5703405   /m/0256539   tt0009064
68637     Q5703405   /m/0256539   tt0094674
1523       Q637137    /m/025wj_   tt0217729
1524       Q637137    /m/025wj_   tt0236617
155982    Q5520925   /m/025z19h   tt0886672
144192    Q5520925   /m/025z19h   tt0245911
40867      Q704353   /m/02612lv   tt0114327
40866      Q704353   /m/02612lv   tt0103369
155784    Q2179767   /m/026q_d7   tt0035828
23987     Q2179767   /m/026q_d7   tt0032420
103974    Q3651415   /m/026qktj   tt0007769
156457    Q3651415   /m/026qktj   tt0036738
156123    Q7387748   /m/026xsmh   tt0187520
53548     Q7387748   /m/026xsmh   tt0275708
154018    Q3961156   /m/027fq8g  tt12699780
7232      Q3961156   /m/027fq8g   tt0077108
147450    Q6827970   /m/0283q6k   tt0047233
147451    Q6827969   /m/0283q6k   tt0054082
156588    Q1784016    /m/0297td  tt13491734
24502     Q1784016    /m/0297td   tt0045421

In [45]:
# Pour l'instant, aucune valeur dupliquée
movies = movies_raw.merge(ids.drop_duplicates(['freebase_ID']), on='freebase_ID', how='left', validate='1:1')
movies.head()

,wikipedia_ID,freebase_ID,name,release_date,box_office,runtime,languages,countries,genres,wikidata_ID,IMDB_ID
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science...",Q261700,tt0228333
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp...",Q16250726,tt0245916
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D...",Q4978832,tt0094806
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic...",Q7995657,tt0094320
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}",Q869644,tt0083949

In [26]:
print(f'{movies.IMDB_ID.notna().mean()*100:.2f}% of movies in this database have corresponding Wikidata and IMDB pages.')

90.23% of movies in this database have corresponding Wikidata and IMDB pages.

In [27]:
movies.IMDB_ID.isna().sum()

7986